
import os
import json
import urllib.request
import pandas as pd
import time

# this code can be used to consolidate csv files present in one folder

start_index = 5000 #mention start index for first folder
interval = 499 #specify interval between start and end index (for eg. 2000-2499; interval is 499)
end_index= start_index+interval 

number_of_folders = 3 #total number of folders to be consolidated

working_directory= str('C:/consolidation')
os.chdir(working_directory) # Change to working directory

#declaring dataframe for consolidated dataframe
Investors_details=pd.DataFrame()
Funds_details=pd.DataFrame()
Investments_detail=pd.DataFrame()
Company_Details_=pd.DataFrame()
Company_FundingRounds_=pd.DataFrame()
Company_FundingRounds_Investors_=pd.DataFrame()
Company_FundingRounds_Investors_Partners_=pd.DataFrame()
Company_Acquisitions_=pd.DataFrame()
Company_Offices_=pd.DataFrame()
Company_Headquarters_=pd.DataFrame()
Company_SubOrganizations_=pd.DataFrame()
Company_Founders_=pd.DataFrame()
Company_Founders_Degrees_=pd.DataFrame()
Company_Founders_FoundedCompanies_=pd.DataFrame()
Company_Founders_Websites_=pd.DataFrame()
Company_Founders_AdvisoryRoles_=pd.DataFrame()
Company_Founders_Investments_=pd.DataFrame()
Company_BoardMembers_=pd.DataFrame()
Company_BoardMembers_Degrees_=pd.DataFrame()
Company_BoardMembers_Jobs_=pd.DataFrame()
Company_BoardMembers_FoundedCompanies_=pd.DataFrame()
Company_BoardMembers_Websites_=pd.DataFrame()
Company_BoardMembers_AdvisoryRoles_=pd.DataFrame()
Company_BoardMembers_Investments_=pd.DataFrame()
Company_FeaturedTeam_=pd.DataFrame()
Company_FeaturedTeam_Degrees_=pd.DataFrame()
Company_FeaturedTeam_Jobs_=pd.DataFrame()
Company_FeaturedTeam_FoundedCompanies_=pd.DataFrame()
Company_FeaturedTeam_Websites_=pd.DataFrame()
Company_FeaturedTeam_AdvisoryRoles_=pd.DataFrame()
Company_FeaturedTeam_Investments_=pd.DataFrame()
Company_PastTeam_=pd.DataFrame()
Company_PastTeam_Degrees_=pd.DataFrame()
Company_PastTeam_Jobs_=pd.DataFrame()
Company_PastTeam_FoundedCompanies_=pd.DataFrame()
Company_PastTeam_Websites_=pd.DataFrame()
Company_PastTeam_AdvisoryRoles_=pd.DataFrame()
Company_PastTeam_Investments_=pd.DataFrame()
Company_CurrentTeam_=pd.DataFrame()
Company_CurrentTeam_Degrees_=pd.DataFrame()
Company_CurrentTeam_Jobs_=pd.DataFrame()
Company_CurrentTeam_FoundedCompanies_=pd.DataFrame()
Company_CurrentTeam_Websites_=pd.DataFrame()
Company_CurrentTeam_AdvisoryRoles_=pd.DataFrame()
Company_CurrentTeam_Investments_=pd.DataFrame()
Company_Members_=pd.DataFrame()
Company_Members_Degrees_=pd.DataFrame()
Company_Members_Jobs_=pd.DataFrame()
Company_Members_FoundedCompanies_=pd.DataFrame()
Company_Members_Websites_=pd.DataFrame()
Company_Members_AdvisoryRoles_=pd.DataFrame()
Company_Members_Investments_=pd.DataFrame()


 



for folder in range(number_of_folders):
    folder_location_name = str(str(start_index)+' to '+str(end_index))
    #iterating through different folder
    os.chdir('C:/consolidation'  + '/' + folder_location_name)
    #concatenating dataframes 
    Investors_details=pd.concat([Investors_details,pd.read_csv('Investors_details.csv')],ignore_index=True)
    Funds_details=pd.concat([Funds_details,pd.read_csv('Funds_details.csv')],ignore_index=True)
    Investments_detail=pd.concat([Investments_detail,pd.read_csv('Investments_detail.csv')],ignore_index=True)
    Company_Details_=pd.concat([Company_Details_,pd.read_csv('Company_Details_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FundingRounds_=pd.concat([Company_FundingRounds_,pd.read_csv('Company_FundingRounds_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FundingRounds_Investors_=pd.concat([Company_FundingRounds_Investors_,pd.read_csv('Company_FundingRounds_Investors_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FundingRounds_Investors_Partners_=pd.concat([Company_FundingRounds_Investors_Partners_,pd.read_csv('Company_FundingRounds_Investors_Partners_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Acquisitions_=pd.concat([Company_Acquisitions_,pd.read_csv('Company_Acquisitions_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Offices_=pd.concat([Company_Offices_,pd.read_csv('Company_Offices_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Headquarters_=pd.concat([Company_Headquarters_,pd.read_csv('Company_Headquarters_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_SubOrganizations_=pd.concat([Company_SubOrganizations_,pd.read_csv('Company_SubOrganizations_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Founders_=pd.concat([Company_Founders_,pd.read_csv('Company_Founders_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Founders_Degrees_=pd.concat([Company_Founders_Degrees_,pd.read_csv('Company_Founders_Degrees_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Founders_FoundedCompanies_=pd.concat([Company_Founders_FoundedCompanies_,pd.read_csv('Company_Founders_FoundedCompanies_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Founders_Websites_=pd.concat([Company_Founders_Websites_,pd.read_csv('Company_Founders_Websites_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Founders_AdvisoryRoles_=pd.concat([Company_Founders_AdvisoryRoles_,pd.read_csv('Company_Founders_AdvisoryRoles_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Founders_Investments_=pd.concat([Company_Founders_Investments_,pd.read_csv('Company_Founders_Investments_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_=pd.concat([Company_BoardMembers_,pd.read_csv('Company_BoardMembers_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_Degrees_=pd.concat([Company_BoardMembers_Degrees_,pd.read_csv('Company_BoardMembers_Degrees_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_Jobs_=pd.concat([Company_BoardMembers_Jobs_,pd.read_csv('Company_BoardMembers_Jobs_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_FoundedCompanies_=pd.concat([Company_BoardMembers_FoundedCompanies_,pd.read_csv('Company_BoardMembers_FoundedCompanies_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_Websites_=pd.concat([Company_BoardMembers_Websites_,pd.read_csv('Company_BoardMembers_Websites_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_AdvisoryRoles_=pd.concat([Company_BoardMembers_AdvisoryRoles_,pd.read_csv('Company_BoardMembers_AdvisoryRoles_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_BoardMembers_Investments_=pd.concat([Company_BoardMembers_Investments_,pd.read_csv('Company_BoardMembers_Investments_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_=pd.concat([Company_FeaturedTeam_,pd.read_csv('Company_FeaturedTeam_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_Degrees_=pd.concat([Company_FeaturedTeam_Degrees_,pd.read_csv('Company_FeaturedTeam_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_Jobs_=pd.concat([Company_FeaturedTeam_Jobs_,pd.read_csv('Company_FeaturedTeam_Jobs_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_FoundedCompanies_=pd.concat([Company_FeaturedTeam_FoundedCompanies_,pd.read_csv('Company_FeaturedTeam_FoundedCompanies_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_Websites_=pd.concat([Company_FeaturedTeam_Websites_,pd.read_csv('Company_FeaturedTeam_Websites_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_AdvisoryRoles_=pd.concat([Company_FeaturedTeam_AdvisoryRoles_,pd.read_csv('Company_FeaturedTeam_AdvisoryRoles_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_FeaturedTeam_Investments_=pd.concat([Company_FeaturedTeam_Investments_,pd.read_csv('Company_FeaturedTeam_Investments_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_=pd.concat([Company_PastTeam_,pd.read_csv('Company_PastTeam_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_Degrees_=pd.concat([Company_PastTeam_Degrees_,pd.read_csv('Company_PastTeam_Degrees_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_Jobs_=pd.concat([Company_PastTeam_Jobs_,pd.read_csv('Company_PastTeam_Jobs_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_FoundedCompanies_=pd.concat([Company_PastTeam_FoundedCompanies_,pd.read_csv('Company_PastTeam_FoundedCompanies_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_Websites_=pd.concat([Company_PastTeam_Websites_,pd.read_csv('Company_PastTeam_Websites_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_AdvisoryRoles_=pd.concat([Company_PastTeam_AdvisoryRoles_,pd.read_csv('Company_PastTeam_AdvisoryRoles_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_PastTeam_Investments_=pd.concat([Company_PastTeam_Investments_,pd.read_csv('Company_PastTeam_Investments_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_=pd.concat([Company_CurrentTeam_,pd.read_csv('Company_CurrentTeam_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_Degrees_=pd.concat([Company_CurrentTeam_Degrees_,pd.read_csv('Company_CurrentTeam_Degrees_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_Jobs_=pd.concat([Company_CurrentTeam_Jobs_,pd.read_csv('Company_CurrentTeam_Jobs_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_FoundedCompanies_=pd.concat([Company_CurrentTeam_FoundedCompanies_,pd.read_csv('Company_CurrentTeam_FoundedCompanies_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_Websites_=pd.concat([Company_CurrentTeam_Websites_,pd.read_csv('Company_CurrentTeam_Websites_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_AdvisoryRoles_=pd.concat([Company_CurrentTeam_AdvisoryRoles_,pd.read_csv('Company_CurrentTeam_AdvisoryRoles_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_CurrentTeam_Investments_=pd.concat([Company_CurrentTeam_Investments_,pd.read_csv('Company_CurrentTeam_Investments_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_=pd.concat([Company_Members_,pd.read_csv('Company_Members_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_Degrees_=pd.concat([Company_Members_Degrees_,pd.read_csv('Company_Members_Degrees_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_Jobs_=pd.concat([Company_Members_Jobs_,pd.read_csv('Company_Members_Jobs_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_FoundedCompanies_=pd.concat([Company_Members_FoundedCompanies_,pd.read_csv('Company_Members_FoundedCompanies_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_Websites_=pd.concat([Company_Members_Websites_,pd.read_csv('Company_Members_Websites_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_AdvisoryRoles_=pd.concat([Company_Members_AdvisoryRoles_,pd.read_csv('Company_Members_AdvisoryRoles_'+ folder_location_name +'.csv')],ignore_index=True)
    Company_Members_Investments_=pd.concat([Company_Members_Investments_,pd.read_csv('Company_Members_Investments_'+ folder_location_name +'.csv')],ignore_index=True)
    
    #increasing index for next folder
    start_index=start_index+ interval+1
    end_index= start_index+ interval

#changing directory to folder where consolidated files has to be created   
os.chdir('C:/consolidation/consolidation') #folder for consolidated files

#creating consolidated file
Investors_details.drop_duplicates().to_csv('Investors_details.csv')
Funds_details.drop_duplicates().to_csv('Funds_details.csv')
Investments_detail.drop_duplicates().to_csv('Investments_detail.csv')
Company_Details_.drop_duplicates().to_csv('Company_Details' +'.csv')
Company_FundingRounds_.drop_duplicates().to_csv('Company_FundingRounds' +'.csv')
Company_FundingRounds_Investors_.drop_duplicates().to_csv('Company_FundingRounds_Investors' +'.csv')
Company_FundingRounds_Investors_Partners_.drop_duplicates().to_csv('Company_FundingRounds_Investors_Partners' +'.csv')
Company_Acquisitions_.drop_duplicates().to_csv('Company_Acquisitions' +'.csv')
Company_Offices_.drop_duplicates().to_csv('Company_Offices' +'.csv')
Company_Headquarters_.drop_duplicates().to_csv('Company_Headquarters' +'.csv')
Company_SubOrganizations_.drop_duplicates().to_csv('Company_SubOrganizations' +'.csv')
Company_Founders_.drop_duplicates().to_csv('Company_Founders' +'.csv')
Company_Founders_Degrees_.drop_duplicates().to_csv('Company_Founders_Degrees' +'.csv')
Company_Founders_FoundedCompanies_.drop_duplicates().to_csv('Company_Founders_FoundedCompanies' +'.csv')
Company_Founders_Websites_.drop_duplicates().to_csv('Company_Founders_Websites' +'.csv')
Company_Founders_AdvisoryRoles_.drop_duplicates().to_csv('Company_Founders_AdvisoryRoles' +'.csv')
Company_Founders_Investments_.drop_duplicates().to_csv('Company_Founders_Investments' +'.csv')
Company_BoardMembers_.drop_duplicates().to_csv('Company_BoardMembers' +'.csv')
Company_BoardMembers_Degrees_.drop_duplicates().to_csv('Company_BoardMembers_Degrees' +'.csv')
Company_BoardMembers_Jobs_.drop_duplicates().to_csv('Company_BoardMembers_Jobs' +'.csv')
Company_BoardMembers_FoundedCompanies_.drop_duplicates().to_csv('Company_BoardMembers_FoundedCompanies' +'.csv')
Company_BoardMembers_Websites_.drop_duplicates().to_csv('Company_BoardMembers_Websites' +'.csv')
Company_BoardMembers_AdvisoryRoles_.drop_duplicates().to_csv('Company_BoardMembers_AdvisoryRoles' +'.csv')
Company_BoardMembers_Investments_.drop_duplicates().to_csv('Company_BoardMembers_Investments' +'.csv')
Company_FeaturedTeam_.drop_duplicates().to_csv('Company_FeaturedTeam' +'.csv')
Company_FeaturedTeam_Degrees_.drop_duplicates().to_csv('Company_FeaturedTeam_Degrees' +'.csv')
Company_FeaturedTeam_Jobs_.drop_duplicates().to_csv('Company_FeaturedTeam_Jobs' +'.csv')
Company_FeaturedTeam_FoundedCompanies_.drop_duplicates().to_csv('Company_FeaturedTeam_FoundedCompanies' +'.csv')
Company_FeaturedTeam_Websites_.drop_duplicates().to_csv('Company_FeaturedTeam_Websites' +'.csv')
Company_FeaturedTeam_AdvisoryRoles_.drop_duplicates().to_csv('Company_FeaturedTeam_AdvisoryRoles' +'.csv')
Company_FeaturedTeam_Investments_.drop_duplicates().to_csv('Company_FeaturedTeam_Investments' +'.csv')
Company_PastTeam_.drop_duplicates().to_csv('Company_PastTeam' +'.csv')
Company_PastTeam_Degrees_.drop_duplicates().to_csv('Company_PastTeam_Degrees' +'.csv')
Company_PastTeam_Jobs_.drop_duplicates().to_csv('Company_PastTeam_Jobs' +'.csv')
Company_PastTeam_FoundedCompanies_.drop_duplicates().to_csv('Company_PastTeam_FoundedCompanies' +'.csv')
Company_PastTeam_Websites_.drop_duplicates().to_csv('Company_PastTeam_Websites' +'.csv')
Company_PastTeam_AdvisoryRoles_.drop_duplicates().to_csv('Company_PastTeam_AdvisoryRoles' +'.csv')
Company_PastTeam_Investments_.drop_duplicates().to_csv('Company_PastTeam_Investments' +'.csv')
Company_CurrentTeam_.drop_duplicates().to_csv('Company_CurrentTeam' +'.csv')
Company_CurrentTeam_Degrees_.drop_duplicates().to_csv('Company_CurrentTeam_Degrees' +'.csv')
Company_CurrentTeam_Jobs_.drop_duplicates().to_csv('Company_CurrentTeam_Jobs' +'.csv')
Company_CurrentTeam_FoundedCompanies_.drop_duplicates().to_csv('Company_CurrentTeam_FoundedCompanies' +'.csv')
Company_CurrentTeam_Websites_.drop_duplicates().to_csv('Company_CurrentTeam_Websites' +'.csv')
Company_CurrentTeam_AdvisoryRoles_.drop_duplicates().to_csv('Company_CurrentTeam_AdvisoryRoles' +'.csv')
Company_CurrentTeam_Investments_.drop_duplicates().to_csv('Company_CurrentTeam_Investments' +'.csv')
Company_Members_.drop_duplicates().to_csv('Company_Members' +'.csv')
Company_Members_Degrees_.drop_duplicates().to_csv('Company_Members_Degrees' +'.csv')
Company_Members_Jobs_.drop_duplicates().to_csv('Company_Members_Jobs' +'.csv')
Company_Members_FoundedCompanies_.drop_duplicates().to_csv('Company_Members_FoundedCompanies' +'.csv')
Company_Members_Websites_.drop_duplicates().to_csv('Company_Members_Websites' +'.csv')
Company_Members_AdvisoryRoles_.drop_duplicates().to_csv('Company_Members_AdvisoryRoles' +'.csv')
Company_Members_Investments_.drop_duplicates().to_csv('Company_Members_Investments' +'.csv')
